# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pablo Ezequiel Inchausti
# title: Software Engineer
title: Software Engineer | University Professor | AWS Community Builder
email: pablo.ezequiel.inchausti@gmail.com
website: inchausti.ar

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: pab_ezequiel
github_username:  pabloin
stackoverflow_username: "5111441"
linkedin_username: pablo-ezequiel-inchausti
youtube_username: pabloezequielinchausti
# youtube_username: globalmtb
# youtube_username: channel/UCrEf7uSPkgAp4AOs2o5TF9g
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: medium
  icon: fas fa-globe
  url: https://pablo-ezequiel.medium.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/pablo_ezequiel_inchausti_gh.jpeg
about_profile_image: images/pablo-ezequiel-inchausti-uade.png
about_content: | 
  Hi, my name's Pablo Ezequiel Inchausti and I'm a software engineer. 

  I like playing chess and grow up in cloud computing. 
  As part of my interests, I am a member of the AWS Community Builder Program 
  and the AWS User Group Leader in Buenos Aires. I believe that communities 
  are one of the best ways to learn and grow together in the AWS ecosystem

  
  And I also love share and learn about last technologies trends throught "The Ninja Project", 
  a great community of ninja's in thech hosted in the company were I work on, BBVA

  I am most skilled in <mark>AWS</mark> and <mark>software development</mark>, 
  and also [I am certified](https://www.credly.com/users/pablo-ezequiel-inchausti/badges), 
  mostly in cloud related technologies 




content:


  - title: Talks
    layout: list
    content:


      - layout: left
        title: AWS User Group Buenos Aires
        caption: 6 mar 2025
        sub_title: Argentina
        description: | 
          [re:Cap 2024](https://www.youtube.com/watch?v=esxSdLmAVgk&t=420s){:target="_video"} 
          
          [meetup](https://www.meetup.com/aws-user-group-buenos-aires/events/306401321/?eventOrigin=group_past_events){:target="_lin"}

          Recap de todos los anuncios de re:Invent 2024

      - layout: left
        title: AWS User Group Buenos Aires
        caption: 10 dic 2024
        sub_title: Argentina
        description: | 
          [Bootcamp Generative AI 2024 - Responsible AI y Guardarails](https://www.youtube.com/live/cNzMwVvgSFg?si=RVFsGp0kIaf88PSB&t=522){:target="_video"} 
          
          [meetup](https://www.meetup.com/aws-user-group-buenos-aires/events/305014460/?eventOrigin=group_events_list){:target="_lin"}

          Con el AWS User Group Buenos Aires compartimos un workshop de Generative AI. 
          En este encuentro hablamos Responsible AI y Seguridad relacionada con Generative AI con Guardarails


      - layout: left
        title: AWS Community Day Argentina 2024
        caption: 26 sept 2024
        sub_title: Argentina
        description: | 
          [AWS Deep Racer: Tips And Tricks](https://www.youtube.com/watch?v=Bqy1IsRktLk&t=378s){:target="_video"} 
          
          [AWS Community Day Home](https://awsarg.org/#user-groups){:target="_lin"}

          En esta charla, se comentarán los "Tips and Tricks" de AWS DeepRacer y entrenar modelos de machine learning
           con tips de "Pro" como utilización de instancias con GPU y uso de DRFC (Deep Racer for Cloud) .



      - layout: left
        title: AWS reInvent Recap 2023
        caption: 29 enero 2024
        sub_title: Argentina
        description: | 
          [AWS reInvent Recap 2023](https://www.youtube.com/watch?v=lFRTj7PQeTs&t=563s){:target="_video"} 
          
          [meetup](https://www.meetup.com/aws-user-group-buenos-aires/events/298285065/?eventOrigin=group_events_list){:target="_lin"}

          re:Cap del evento AWS re:Invent 2023 compartiendo las novedades más importantes y la experiencia de estar ahí.


      - layout: left
        title: AWS GameDay 2023
        caption: 11 octubre 2023
        sub_title: Argentina
        description: | 
          [Workshop AWS GameDay 2023 - Buenos Aires - Córdoba](https://www.youtube.com/watch?v=X23cQyTUdNw&t=574s){:target="_video"} 
          
          [meetup](https://www.meetup.com/aws-user-group-buenos-aires/events/296259050/?eventOrigin=group_events_list){:target="_lin"}

          Workshop de entrenamiento para el AWS GameDay 2023 organizado en con los User Groups de Buenos Aires y Córdoba.
          Participaron 9 equipos de cuatro personas y se realizó en las instalaciones de Plataforma 10 y Teracloud.



      - layout: left
        title: Nerdearla 2023
        caption: 26 sept 2023
        sub_title: Argentina
        description: | 
          [Racing with AWS DeepRacer Student](https://www.youtube.com/watch?v=Bqy1IsRktLk&t=378s){:target="_video"} 
          
          [swapcard](https://app.swapcard.com/event/nerdearla-2023/planning/UGxhbm5pbmdfMTUzNjYzNA==){:target="_lin"}

          Workshop de "AWS DeepRacer" junto a Matías Kreder, finalista de AWS DeepRacer en AWS Re:Invent Las Vegas. 
          Participaron más de 180 personas.

      - layout: left
        title: Nerdearla 2023
        caption: 27 sept 2023
        sub_title: Argentina
        description: | 
          [El Ciclo de Testing en Web y Mobile](https://www.youtube.com/watch?v=98dxJWUWPFo&list=PLTTdzfRyGY1uK1Ss5R4j_SF63p7qVd0bI&index=40){:target="_video"} 

          [swapcard](https://app.swapcard.com/event/nerdearla-2023/planning/UGxhbm5pbmdfMTUzNjU4NQ==){:target="_lin"}

          
          Charla spondor de BBVA Argentina en Nerdearla, Junto a José Antonio Guerrero. Participaron en línea más de 500 personas


      - layout: left
        title: AWS Community Day Argentina
        caption: 16 sept 2023
        sub_title: Universidad Siglo XXI - Cordoba
        description: | 
          [Reinforce Learning in AWS DeepRacer](https://www.youtube.com/watch?v=ldPVludPCyw&t=19414s){:target="_video"} 

          Dictado en el AWS Community Day de Argentina, de la charla y el workshop de AWS DeepRacer

      - layout: left
        title: AWS User Group Buenos Aires
        caption: Agosto 29, 2023
        sub_title: Presencial, en las oficinas de AWS Argentina
        description: | 
          [Generative AI - SageMaker](https://www.youtube.com/live/JhN0SbRNt64?si=Qq4CNQmGwEgf4M7_&t=2315){:target="_video"} 

          Junto a Ricardo Ceci compartimos contenidos de Inteligencia Artificial en un Meet UP del AWS User Group Buenos Aires, 
          realizado de forma presencial en las oficinas de AWS Argentina con casi 50 personas presentes.
          En los contenidos, Ricardo habló sobre "Generative AI" y yo sobre "SageMaker"

      - layout: left
        title: AWS Cloud Practitioner Challenge
        caption: Abril a Junio de 2023
        sub_title: Canal Youtube - AWS User Group Buenos Aires
        description: | 
          Con el AWS User Group Bueno Aires dimos el #Challenge para la certificación de Cloud Practitioner
          Con más de 400 usuarios en línea cada semana y casi 80 personas que lograron pasar su certificación
          Transmición en vivo por Youtube e interacción con la comunidad por Discord
          
          Dictando contenidos:

          - Apr 26, 2023 [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE Sesion 0](https://www.youtube.com/live/156Qovhl9tk?si=0QhDLLRqY0GtvR-S&t=1941){:target="_video"} 

          - May 3, 2023 [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE Sesion 1 "IAM"](https://www.youtube.com/watch?v=j01Klr4fBkc&list=PLMg_LIgq4KWfR3bBVwgayGVuhbDItJzp8&index=2){:target="_video"} 

          - May 17, 2023 [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE Sesión 3 "EC2"](https://www.youtube.com/watch?v=bXtb3YViJLA&list=PLMg_LIgq4KWfR3bBVwgayGVuhbDItJzp8&index=4){:target="_video"} 

          - May 24, 2023 [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE Sesión 4 "AWS Elastic Load Balancers y Auto Scaling"](https://www.youtube.com/watch?v=b4_OMyQHXgU&list=PLMg_LIgq4KWfR3bBVwgayGVuhbDItJzp8&index=6){:target="_video"} 

          - Jul 12, 2023 [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE Sesión 5 "Storage (EBS, EFS, S3) + Monitoring/Log"](https://www.youtube.com/watch?v=GqYKhnqDDeI&list=PLMg_LIgq4KWfR3bBVwgayGVuhbDItJzp8&index=7){:target="_video"} 

          - Jul 12, 2023 [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE Sesión 11 "TIPS""](https://www.youtube.com/watch?v=lnPkemd01LM&list=PLMg_LIgq4KWfR3bBVwgayGVuhbDItJzp8&index=13){:target="_video"} 

          Playlist Completa:
          - [AWS UG BS AS: AWS CLOUD PRACTITIONER CHALLENGE](https://www.youtube.com/playlist?list=PLMg_LIgq4KWfR3bBVwgayGVuhbDItJzp8){:target="_video"}

      - layout: left
        title: AWS User Group Buenos Aires
        caption: Febrero 8, 2023
        sub_title: Canal Youtube "Cloud en Español"
        description: | 
          [Recap Re:Invent 2022](https://www.youtube.com/watch?v=jRFe2KXk5AU){:target="_video"}

          Junto a Ricardo Ceci y Gastón Silbestein compartimos el re:Cap del evento AWS re:Invent 2022 dirigido a la comunidad de AWS User Group Buenos Aires


      - layout: left
        title: Nerdearla 2022
        caption: October 21, 2022
        sub_title: Argentina
        description: | 
          [Esencial en AWS: Construir una VPC desde cero](https://www.youtube.com/watch?v=TRKkGYHQumQ){:target="_video"} 
          
          In this workshop, we build a VPC from scratch in AWS. While we are creating the VPC, we will be learning about Route Tables, NACL, Security Groups, Nat Gateways and Nat Instances, Ephemeral ports, and more. 
          
          Finally, we will deploy a dynamic web site with their database in the VPC to verify that all is correctly configured.
          The talk was given in the context of the AWS Community Builder program.

      - layout: left
        title: Nerdearla 2022
        caption: October 21, 2022
        sub_title: Argentina
        description: | 
          - [Microfrontends en un Banco Global](https://www.youtube.com/watch?v=hBYgnElAtw4){:target="_video"} 

          - [Entrevista "En vivo desde Nerdearla"](https://www.youtube.com/watch?v=_f5cXuAMvI4&t=2150s){:target="_lin"}

          Cón más de 500 personas en línea, en esta charla compartimos acerrca de las iniciativas que se llevan adelante en el BBVA a nivel global con Micro Frontends. La charla corresponde al espacio sponsor del BBVA en Nerdearla 2022 


      - layout: left
        title: 50 JAIIO - ASSE
        caption: October 21, 2022
        sub_title: Argentina
        description: | 
          [Microfrontends en un Banco Global](https://www.youtube.com/watch?v=1OXVz_mkMX4&t=21372s){:target="_video"} 
          
          Presentamos en la 50 JAIIO la charla de "Micro Frontends" para describir lo que se está haciendo en el BBVA con esta tecnología.
          Espacio Sponsor del BBVA Argentina dentro del Congreso.

      - layout: left
        title: BBVA Argentina
        caption: October 20, 2020
        sub_title: The Ninja Project
        description: | 
          [AWS Essencials - Taller Pre Ninja Hack](https://www.youtube.com/watch?v=X8BqUbiZtlM&list=PLMLI9YiS7TLsEEAN-IOU6kz7-DSNsOLu8&index=5){:target="_video"} 
          
          Workshop de preparación en AWS dirigido a los participantes del Hackathon Ninja del BBVA en los países donde tiene presencia en LATAM: Argentina, Uruguay, Colombia, México, Venezuela, Perú con más de 300 asistentes



  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Glaciar.org
        link: github.com/glaciar-org
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is "Glaciar" a software to visualize open data about water and environmental information and give quality information
        description: | 
          I did this project in 2018-2019 as the final Thesis of a Master in Techinolgy 


  - title: Education
    layout: list
    content:
      - layout: left
        title: UADE
        caption: 2018 - 2020
        sub_title: Maestría en Tecnología y Comunicaciones
        quote: >
          Universidad Argentina de la Empresa
        description: | 
          Study in UADE was not only return to the university, but also a grow up time in personal and profeesional way

          After [finished my studies in UADE](https://www.uade.edu.ar/sites/business-school/maestrias-y-doctorado/maestria-en-tecnologia-informatica-y-de-comunicaciones-tic/testimonios/){:target="_lin"} I have the opportunity to became a techer 

      - layout: left
        title: UNS
        caption: 1994 - 2000
        sub_title: Licenciatura en Ciencias de la Computación
        quote: >
          Universidad Nacional del Sur
        description: | 
          A great university in my city, Bahia Blanca, after finished my studies I move to Buenos Aires to start my professional career

  - title: Experience
    layout: list
    content:
      - layout: left
        title: BBVA
        link: bbva.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: 2001 - Present
        quote: >
          Engineering ~ Argentina
        description: | 
          The technology is crucial in the finantial sector and crucial for an excelent client relation. In the bank I worked in may roles related to the digital chanles, like software development web and mobile for retail and corporate, and roles with devops and software architecture 

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests as software engineering some of my other interests and hobbies are:
      - Chess player! - May be we could meet on [lichess](https://lichess.org/pabloin){:target="_chess"}!
      - Love Diving when I have the chance
      - AWS Communit Builder and AWS User Group Leader
      - [There is a Ninja'story on me!](https://www.bbva.com/es/ar/innovacion/el-primer-cinturon-negro-del-proyecto-ninja-de-bbva/){:target="_noticia"}

# Look at this cool image  
# ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on request (v1.0)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
